export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  // OPTIONS request handle කරන්න
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  // GET request - API status
  if (req.method === 'GET') {
    return res.status(200).json({ 
      message: 'ZentryCloud API is running ✅',
      status: 'active',
      endpoints: {
        generate: 'POST /api/generate-config'
      }
    });
  }
  
  // POST request පමණක් accept කරන්න
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }
  
  try {
    const { isp, package: pkg, app: appType, sni } = req.body;
    
    // Validation
    if (!isp) {
      return res.status(400).json({ error: 'ISP එකක් තෝරන්න' });
    }
    
    // Config generate කරන්න
    const timestamp = new Date().toISOString();
    const config = `==============================
ZENTRYCLOUD VPN CONFIG
==============================
🌏 Node: SG-ULTRA01 (Singapore)
📡 ISP: ${isp}
📦 Package: ${pkg || 'Default'}
📱 App: ${appType || 'Netmod'}
💾 Data: 10GB
⏰ Validity: 7 Days
${sni ? `🔧 Custom SNI: ${sni}` : ''}
==============================
✅ Generated by ZentryCloud
📅 Generated: ${timestamp}
==============================`;
    
    res.status(200).json({ 
      success: true,
      config: config 
    });
    
  } catch (error) {
    res.status(500).json({ error: 'Internal server error: ' + error.message });
  }
}
