const express = require('express');
const app = express();
app.use(express.json());

app.post('/api/generate-config', (req, res) => {
  const { isp, package: pkg, app: appType, sni } = req.body;
  
  if (!isp) {
    return res.status(400).json({ error: 'ISP එකක් තෝරන්න' });
  }
  
  const config = `==============================
D FREE VPN CONFIG
==============================
🌏 Node: SG-ULTRA01 (Singapore)
📡 ISP: ${isp}
📦 Package: ${pkg}
📱 App: ${appType}
💾 Data: 10GB
⏰ Validity: 7 Days
${sni ? `🔧 Custom SNI: ${sni}` : ''}
==============================
✅ Generated by D FREE VPN
==============================`;
  
  res.json({ config: config });
});

app.get('/', (req, res) => {
  res.send('D FREE VPN API is running ✅');
});

app.listen(3000, () => {
  console.log('Server ready on port 3000');
});
