export async function onRequest(context) {
  const { request } = context;
  
  // CORS headers - mobile apps එකට allow කරන්න
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json'
  };
  
  // OPTIONS request (preflight)
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers });
  }
  
  // GET request - API status
  if (request.method === 'GET') {
    return new Response(JSON.stringify({
      status: "OK",
      message: "ZentryCloud Backend Running 🚀",
      usage: "Send POST request with ISP, package, app, sni"
    }), { status: 200, headers });
  }
  
  // POST request පමණක් accept කරන්න
  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed. Use POST.' }), 
      { status: 405, headers });
  }
  
  try {
    const body = await request.json();
    const { isp, package: pkg, app: appType, sni } = body || {};
    
    // Validation - ISP එකක් තෝරාගෙන තියෙනවද?
    if (!isp) {
      return new Response(JSON.stringify({ error: 'කරුණාකර ISP එකක් තෝරන්න' }), 
        { status: 400, headers });
    }
    
    // Config එක generate කරන්න
    const timestamp = new Date().toLocaleString('en-LK', { timeZone: 'Asia/Colombo' });
    const config = `==============================
🔰 ZENTRYCLOUD VPN CONFIGURATION 🔰
==============================
🌏 Node        : SG-ULTRA01 (Singapore)
📡 ISP         : ${isp}
📦 Package     : ${pkg || 'Default'}
📱 App         : ${appType || 'Netmod'}
💾 Data Limit  : 10GB
⏰ Validity    : 7 Days
📅 Generated   : ${timestamp}
${sni ? `🔧 Custom SNI  : ${sni}` : '🔧 SNI         : Auto (Cloudflare)'}
==============================
🔗 Server      : sg-free.zentrycloud.com
🛡️ Security    : TLS + WebSocket
⚡ Protocol    : VMESS / VLESS
==============================
✅ Config generated by ZentryCloud
🇱🇰 Free Community VPN for Sri Lanka
🔔 Join Telegram: @ZentryCloud
==============================

📱 How to use:
1. Copy this config
2. Open Netmod / V2Box app
3. Import from clipboard
4. Connect and enjoy! 🚀`;

    return new Response(JSON.stringify({ 
      success: true, 
      config: config 
    }), { status: 200, headers });
    
  } catch (error) {
    return new Response(JSON.stringify({ 
      error: 'Server error: ' + error.message 
    }), { status: 500, headers });
  }
}
