export default async function handler(req, res) {
  // CORS headers - mobile apps එකට ඉඩ දෙන්න
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  // OPTIONS request (preflight) handle කරන්න
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  // GET request ආවොත් API status එක පෙන්වන්න
  if (req.method === 'GET') {
    return res.status(200).json({
      status: "OK",
      message: "ZentryCloud Backend Running 🚀",
      usage: "Send POST request to this endpoint with ISP, package, app, sni"
    });
  }
  
  // POST request පමණක් accept කරන්න
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }
  
  try {
    const { isp, package: pkg, app: appType, sni } = req.body || {};
    
    // Validation - ISP එකක් තෝරාගෙන තියෙනවද?
    if (!isp) {
      return res.status(400).json({ error: 'කරුණාකර ISP එකක් තෝරන්න' });
    }
    
    // Config එක generate කරන්න
    const timestamp = new Date().toLocaleString('en-LK', { timeZone: 'Asia/Colombo' });
    const config = `==============================
🔰 ZENTRYCLOUD VPN CONFIGURATION 🔰
==============================
🌏 Node        : SG-ULTRA01 (Singapore)
📡 ISP         : ${isp}
📦 Package     : ${pkg || 'Default'}
📱 App         : ${appType || 'Netmod'}
💾 Data Limit  : 10GB
⏰ Validity    : 7 Days
📅 Generated   : ${timestamp}
${sni ? `🔧 Custom SNI  : ${sni}` : '🔧 SNI         : Auto (Cloudflare)'}
==============================
🔗 Server      : sg-free.zentrycloud.com
🛡️ Security    : TLS + WebSocket
⚡ Protocol    : VMESS / VLESS
==============================
✅ Config generated by ZentryCloud
🇱🇰 Free Community VPN for Sri Lanka
🔔 Join Telegram: @ZentryCloud
==============================

📱 How to use:
1. Copy this config
2. Open Netmod / V2Box app
3. Import from clipboard
4. Connect and enjoy! 🚀`;

    return res.status(200).json({ 
      success: true,
      config: config,
      message: "Config generated successfully!"
    });
    
  } catch (error) {
    console.error('Error:', error);
    return res.status(500).json({ 
      error: 'Server error: ' + error.message 
    });
  }
}
